language: node_js

node_js:
  - node

cache: yarn

services:
  - docker

##
# Currently getting mismatch errors. Temporarily disabling Backstop tests in Travis.
##

# before_install:
# - docker pull backstopjs/backstopjs:latest

script:
- yarn
- yarn test:jest
- yarn test:cypress

##
# Need to configure Travis artifacts to debug issue with Backstop tests in CI.
##

# addons:
#   artifacts: true
  